### ISSUE TITLE
Repair function not working

### ISSUE THREAD

**Issue by impressiveinfantry** [msummers123/Movecraft-3#111] opened 2015-03-25 21:15 UTC
i had to create another issue because the original one is too long. For you msummers: here is the config you requested: Locale: en
CompatibilityMode: false
SinkRateTicks: 20
SinkCheckTicks: 100
TracerRateTicks: 5
PilotTool: 280
WorldGuardBlockMoveOnBuildPerm: true
WorldGuardBlockSinkOnPVPPerm: true
ManOverBoardTimeout: 30
FireballLifespan: 6
DisableSpillProtection: false
RequireCreatePerm: false
TNTContactExplosives: true
DisableCrates: false
FadeWrecksAfter: 30

**Comment by impressiveinfantry** [comment] 2015-03-25 21:16
and the Log as well: [15:11:26] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v6.0;3342-78f975b9
[15:11:27] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[15:11:27] [Server thread/INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_8_R1 as the Bukkit adapter
[15:11:27] [Server thread/INFO]: [Movecraft] Enabling Movecraft v3.1.X78
[15:11:27] [Server thread/INFO]: [Movecraft] Recognized PilotTool setting of: 280
[15:11:27] [Server thread/INFO]: [Movecraft] CompatiblityMode is set to false
[15:11:27] [Server thread/INFO]: [Movecraft] Movecraft did not find a compatible version of WorldGuard. Disabling WorldGuard integration
[15:11:27] [Server thread/INFO]: [Movecraft] Found a compatible version of WorldEdit. Enabling WorldEdit integration
[15:11:27] [Server thread/INFO]: [Movecraft] Could not find compatible Vault plugin. Disabling Vault integration.
[15:11:27] [Server thread/INFO]: [Movecraft] Loaded 22 Craft files
[15:11:27] [Server thread/INFO]: [Movecraft] Submitted statistics to mcstats.org succesfully. Thank you for your support.
[15:11:27] [Server thread/INFO]: [Movecraft] [V 3.1.X78] has been enabled.
[15:11:27] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[15:11:27] [Server thread/INFO]: Done (3.299s)! For help, type "help" or "?"
[15:11:27] [Craft Scheduler Thread - 2/INFO]: [Vault] Checking for Updates ... 
[15:11:28] [Craft Scheduler Thread - 2/INFO]: [Vault] No new version available

**Comment by msummers123** [comment] 2015-03-25 21:22
Really? it gave you an error? I've never seen that. Here was my response from the other issue:
Ok, cool, thanks. Yeah, you are actually already mostly ready to go. Worldedit integration is working, and that is the important one. Just add this to your config.yml:
RepairTicksPerBlock: 10
If you are worried about miss-spelling it or otherwise screwing up the config, simply delete the config.yml and restart your server. It will automatically make a new one with the new options.

If you want to charge players with in-game currency via vault, you will need a newer version of vault. Here is exact build I used: http://dev.bukkit.org/bukkit-plugins/vault/files/49-vault-1-5-2/

Although it should work with anything after 1.5. Looks like you still have an old build of 1.4

**Comment by impressiveinfantry** [comment] 2015-03-25 21:25
i am running vault version 1.5.3 just so ya know

**Comment by msummers123** [comment] 2015-03-25 21:27
Ah, I was looking at a previous log you had posted where it said 1.4. Hmmm... that smells like a movecraft bug, if it doesn't like 1.5.3. I will investigate further. Still, with the option I sent you it should work fine. Just not the billing part. If you do want the billing part, you might want to try vault 1.5.2, because thats the build I use on my own server

**Comment by impressiveinfantry** [comment] 2015-03-25 21:30
i will try 1.5.2 if that doesnt work, then its a bug.

**Comment by impressiveinfantry** [comment] 2015-03-25 21:35
i tried all of the vault plugins 1.5 and above and none of them work. guess thats another bug your going to have to fix

**Comment by impressiveinfantry** [comment] 2015-03-25 23:00
hey msummers1 how does the vault plugin work just fine on your server yet doesn't work at all on mine

**Comment by msummers123** [comment] 2015-03-26 15:19
I tried Vault 1.5.3, and had no problems. The core difference between my server bootup log and yours is mine has this line:

[Vault] [Economy] Essentials Economy found: Waiting

I think the issue is you don't have anything that actually uses vault as an economy system (IE: essentials) so it is shutting down. But I think we are over complicating this. I wouldn't worry about it. Just don't use the payment system. You can still have repairs for 0 cost. You don't have any way to give people money anyway, so there is no point in trying to charge people money that they can't earn.

**Comment by impressiveinfantry** [comment] 2015-03-27 00:11
dont worry got it to work btw i want to know how your doing on building your newest ships. I have one question: will the battle cruiser replace the goliath as a practical large warship or will it just be a new addition to your designs

**Comment by msummers123** [comment] 2015-03-27 00:14
What was the solution, in case anyone else has the same thing?

The battle cruiser will replace the goliath for the RN in terms of a practical large warship, but the most heavily armed ship will actually be the new version of the Shadow. Although how much armor it will have remains to be seen. The battle cruiser may end up with more.

**Comment by impressiveinfantry** [comment] 2015-03-27 03:03
Will these designs bee ready by this Sunday or the next airship pirates episode.

**Comment by msummers123** [comment] 2015-03-31 20:00
Both the Shadow refit 2 and the Battlecruiser are scheduled to be done and released with the next Airship Pirates episode, on 4/12. However it is a very ambitious episode and don't be surprised if it is late.

**Closed by msummers123** 2015-03-31 20:00 UTC
