### ISSUE TITLE
Request: Add more support for larger ships

### ISSUE THREAD

**Issue by heavyhussar** [msummers123/Movecraft-3#61] opened 2014-12-09 05:50 UTC
i know some people want to take movecraft to its limits. some people want to build huge ships or aircraft with over 100,00 blocks in total volume or more. but when the block count accedes 35000 there are major issues like crashes and horrible lag. a good example is baccayarro's goliath airship with over 53k blocks in total volume. Absolute lag monster with enough power to crash huge minecraft servers. many people might build even bigger and more ludicrous vessels or airships. more support should be added to those large vessels because people don't always think tiny and minuscule.

**Comment by TylerS1066** [comment] 2015-02-08 20:45
Technically there is a limit on ship size, the size of a java int (around 2 billion)

**Comment by AJCStriker** [comment] 2015-03-19 15:46
@TylerS1066 BigInt classes would let you scale that to any theoretical size on the plugin size. I think you would run into a lot more issues before that one :)

@mwkaicz  @msummers123  From when I initially wrote the algorithm, I designed it to scale in a way that would support ships of a theoretically limitless size. 

There are a few considerations to make when considering what might be causing issues:

1. The algorithm was designed to be parralellized but never was. While ship calculations are done concurrently to the main thread, or at least they used to be, that does not solve all of the headaches. The processing thread does not take into consideration the prolonged effect on the system of having an ongoing, CPU intensive task which could cause degradation of the gameplay during the processing phase. Parallelising the algorithm into discreet containers of 6000 blocks, each executed on a separate thread might reduce this. Further, switching to a Thread Pool method to prevent the number of calculations exceeding CPU limits and possibly preventing the threads from contesting CPU resources with the main server thread.

2. Minecraft was never good at playing ball with the way block updates get sent by the plugin. The games internal data structures and optimisations it attempts to make rely on blocks being modified in small, highly localised areas with large time difference between changes. A good test for whether this is something that could potentially be avoided is "Are there any other plugins that can modify 100,000 blocks without adverse effects on performance?". If there are then there is some hope.

3. The final thing to consider is the amount of memory used when calculating ship movements is absurd. I never looked to far into it as it wasn't a pressing concern, but my guess is that something in the processing code, quite possibly the matrix multiplication, is causing a horrific memory leak. Either that or it legitimately takes lots of memory to process. Either way the solution might be to against break up calculations and push the result over the network before moving onto the next block. This might stop the server getting memory starved which could once again cause issues.

Just my two cents, might help someone do something cool.

**Comment by mwkaicz** [comment] 2015-03-19 17:21
@AJCStriker 
theory is nice, but no one has own datacenter :)
1) Really good suggestion about parsing task to more threads, it should really improve speed of calculations :) But it will be pretty hard to put it together ... maybe Moveceraft V4 ? :)
2) As I know, there are not :(
3) Understand I correctly, that it's about warp? That's the reason why warps are unsecure, (without collision check)?  I've never seen this memory leak yet.

**Comment by AJCStriker** [comment] 2015-03-19 17:30
@mwkaicz Sadly I run a company now so actually finishing the work I started on Movecraft V4 would be a challenge time wise.

It's something I would like to do if I got a window, but it's not a priority.

**Comment by TylerS1066** [comment] 2015-03-19 20:21
@AJCStriker AsyncWorldEdit has a structure that changes millions of blocks, and is fairly efficient, the problem is that it can take 15+ minutes to do.  It does do 3k blocks a second average without any sort of lag.

**Comment by impressiveinfantry** [comment] 2015-03-27 03:05
I tried ascyncworldedit and it didn't work. I do think if movecraft had integration with it though, then it would be a major improvement.

**Comment by TylerS1066** [comment] 2015-03-27 12:11
I was mentioning how AsyncWE has a way to change alot of blocks at once, Movecraft DOES NOT and probably WILL NOT have integration with it.

**Comment by msummers123** [comment] 2015-03-27 15:57
Yeah, although "alot of blocks" is relative. AsyncWE is great in that it doesn't cause lag, but its actually pretty slow with placing blocks. Movecraft can generally handle 10-20k blocks per second, AsyncWE seems to cap out at a few thousand. Movecraft can do additional optimizations unique to moving crafts that don't really apply to AsyncWE.

Although, I'm sure in both cases the real underlying issue is the Minecraft core map updater. Which, despite rumors to the contrary, is still single thread and quite slow. Unless that changes, don't expect radical changes in the block processing speed.

**Comment by msummers123** [comment] 2015-09-01 02:18
Some optimizations were done, most notably in native code mode. I think I've done all I can do on this for now. Closing the ticket.

**Closed by msummers123** 2015-09-01 02:18 UTC
