### ISSUE TITLE
Tracers

### ISSUE THREAD

**Issue by TylerS1066** [msummers123/Movecraft-3#100] opened 2015-03-07 01:59 UTC
So random blocks have been showing up at the edge of my loaded chunks, at first it was small but it's gotten bigger and worse, here are the latest screenshots

The random blocks are only glowstone, cobwebs and 1/2 water blocks.

![2015-03-06_19 50 35](https://cloud.githubusercontent.com/assets/7319776/6539500/390f2f34-c43b-11e4-8b1a-ae5e79931c8e.png)
![2015-03-06_19 50 40](https://cloud.githubusercontent.com/assets/7319776/6539503/391d86f6-c43b-11e4-82a4-fa776da31840.png)
![2015-03-06_19 50 44](https://cloud.githubusercontent.com/assets/7319776/6539502/391d54c4-c43b-11e4-8e2e-2d11b823ae8e.png)
![2015-03-06_19 51 46](https://cloud.githubusercontent.com/assets/7319776/6539504/391fa1e8-c43b-11e4-9d59-3eccd22d1b93.png)
![2015-03-06_19 51 51](https://cloud.githubusercontent.com/assets/7319776/6539505/3920adb8-c43b-11e4-968b-3a55fbe0b995.png)
![2015-03-06_19 51 53](https://cloud.githubusercontent.com/assets/7319776/6539506/39229524-c43b-11e4-85c4-55e972cb2e8a.png)
![2015-03-06_19 51 56](https://cloud.githubusercontent.com/assets/7319776/6539507/39254b0c-c43b-11e4-9eef-9ec00d0c993a.png)
![2015-03-06_19 51 57](https://cloud.githubusercontent.com/assets/7319776/6539509/392a33d8-c43b-11e4-9a85-2174485d0719.png)
![2015-03-06_19 51 58](https://cloud.githubusercontent.com/assets/7319776/6539508/39297a42-c43b-11e4-9cfd-5e29361544d0.png)
![2015-03-06_19 52 02](https://cloud.githubusercontent.com/assets/7319776/6539510/392e7dee-c43b-11e4-8b37-7a3e168a8116.png)
![2015-03-06_19 54 47](https://cloud.githubusercontent.com/assets/7319776/6539511/392ec01a-c43b-11e4-9c82-f6e2dd2c086c.png)
![Uploading 2015-03-06_19.54.49.png . . .]()

**Comment by msummers123** [comment] 2015-03-07 08:07
Yes, this is caused by Minecraft entity behavior and long range cannons. When you fire a cannon out of range, Minecraft stops tracking it, but saves it to the chunk for later use. Then when that chunk is loaded later, the TNT pops back into existence. Typically, this occurs at the edge of your view distance, and you would never know it if not for the tracers. An amusing thing to do if you get bored is to fire a long range gun into the distance repeatedly, then after a large number of shells have been accumulated, move off into the unloaded chunks the TNT flew into. You will then see a huge number of them all going off at once.

The only way to prevent this behavior is to either:

1 - not use long range TNT cannons
2 - turn off tracers (which won't stop the behavior, but will stop you from seeing it)
3 - increase your server view distance so that it is longer than any of your cannons shoot

**Comment by TylerS1066** [comment] 2015-03-07 14:29
I've seen the TNT being hung at the edge of the render distance when I was testing the CST, is the only way to remove it to restart minecraft?

**Comment by msummers123** [comment] 2015-03-07 17:45
If you move into the area the explosions occur in, that seems to work. Having looked at the code again, I might be able to improve this behavior. I will add it to the list.

**Comment by TylerS1066** [comment] 2015-03-07 18:11
Moving into the area hasn't fixed it for me (just realized that I'm issue #100)

**Comment by msummers123** [comment] 2015-03-23 15:23
I think this is fixed in the latest version, but I am not certain. If you could help testing, that would be appreciated.

**Comment by msummers123** [comment] 2015-03-23 15:23
The fix would only affect new shots fired, not previous ones, FYI

**Comment by msummers123** [comment] 2015-04-07 18:47
I think this is fixed in the latest version. Can you test?

**Comment by mwkaicz** [comment] 2015-04-10 05:43
Confirmed

**Closed** 2015-04-10 14:24 UTC
