### ISSUE TITLE
Ships not crashing even though the blocks have been removed.

### ISSUE THREAD

**Issue by striker0822** [msummers123/Movecraft-3#87] opened 2015-02-07 04:14 UTC
Not sure if this is a designed feature, however when I use worldedit to delete the flyblocks of a ship, such as redstone. With the new version It constantly spams my console with (First line) Movecraft error task 23 generated an exception error. Any Ideas? Any ways to fix it?

**Comment by striker0822** [comment] 2015-02-07 04:24
[Piece of console spam]
java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected
	at net.countercraft.movecraft.async.AsyncManager.isRegionBlockedPVP(AsyncManager.java:453) ~[?:?]
	at net.countercraft.movecraft.async.AsyncManager.processSinking(AsyncManager.java:478) ~[?:?]
	at net.countercraft.movecraft.async.AsyncManager.run(AsyncManager.java:776) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-1649]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1649]
[23:17:54] [Server thread/WARN]: [Movecraft] Task #23 for Movecraft v3.1.X70 generated an exception

**Comment by msummers123** [comment] 2015-02-07 15:07
Yeah, this is because it is trying to check WorldGuard for PVP permissions to see if it should allow the craft to sink. This error is caused by an incompatible version of WorldGuard. They changed their API a little while ago, and a version of Movecraft that works with the new one will crash with the old one. Which is rather annoying.

You can either get the new dev build of WorldGuard (but I'm not sure it works in Spigot 1.8), or just disable the WorldGuard integration in Movecraft's config.yml.

**Comment by striker0822** [comment] 2015-02-07 17:52
Ah. Another problem. Joy.
[12:50:30] [Server thread/ERROR]: null
java.lang.NoSuchMethodException: me.blackvein.quests.Quester$1.hardClear(java.lang.Object)
	at java.lang.Class.getMethod(Unknown Source) ~[?:1.7.0_60]
	at me.blackvein.quests.Quester.hardClear(Quester.java:3398) [Quests.jar:?]
	at me.blackvein.quests.Quester.loadData(Quester.java:2507) [Quests.jar:?]
	at me.blackvein.quests.PlayerListener.onPlayerJoin(PlayerListener.java:784) [Quests.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_60]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) [spigot.jar:git-Spigot-1649]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-1649]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [spigot.jar:git-Spigot-1649]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PlayerList.c(PlayerList.java:265) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PlayerList.a(PlayerList.java:152) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.LoginListener.c(LoginListener.java:119) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.LoginListener.a(LoginListener.java:44) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1649]
[12:50:30] [Server thread/INFO]: striker0822[/74.103.113.84:57195] logged in with entity id 135 at ([AirshipDev] -646.1080531602416, 28.0, 631.4933480373326)
[12:50:35] [Server thread/INFO]: striker0822 issued server command: /speed 10
[12:50:37] [Server thread/INFO]: striker0822 issued server command: //paste
[12:50:39] [Server thread/INFO]: striker0822 issued server command: //schem load RNB
[12:50:39] [Server thread/INFO]: [WorldEdit] striker0822 loaded C:\Users\Dakota\Desktop\Server\plugins\WorldEdit\schematics\RNB.schematic
[12:50:40] [Server thread/INFO]: striker0822 issued server command: //paste
[12:50:41] [Server thread/INFO]: striker0822 issued server command: /speed 1
[12:50:44] [Server thread/INFO]: [Movecraft] Player striker0822 piloted a craft of type RNB with size 1575 at location: -603 x, 554 z
[12:50:56] [Server thread/INFO]: striker0822 issued server command: //removenear 152 20
[12:50:59] [Server thread/INFO]: [Movecraft] Player striker0822 has released a craft of type RNB with size 1575 at coordinates : -603 x , 554 z
[12:50:59] [Server thread/WARN]: [Movecraft] Task #24 for Movecraft v3.1.X70 generated an exception
java.lang.NullPointerException
	at net.countercraft.movecraft.async.AsyncManager.processSinking(AsyncManager.java:566) ~[?:?]
	at net.countercraft.movecraft.async.AsyncManager.run(AsyncManager.java:776) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-1649]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1649]
[12:51:04] [Server thread/INFO]: striker0822 issued server command: /region info
[12:51:32] [Timer-1/INFO]: [WorldGuard] Region data changes made in 'AirshipDev' have been background saved
[12:51:33] [Server thread/INFO]: striker0822 lost connection: Disconnected

**Comment by msummers123** [comment] 2015-02-07 23:07
Ah, I see what is going on. It seems there is a bug where if the last craft that exists in a world sinks, but is blocked by PVP protection, it gives that error. It only happens if its the last craft, and only if it is blocked by PVP protection. Although it still does its job, blocking the sinking event, and releasing the craft.

The error itself is harmless. I'll get it fixed as soon as I can, probably next week along with a batch of other fixes. Until then, just ignore it.

**Comment by msummers123** [comment] 2015-02-25 18:26
Fixed in newer version

**Closed by msummers123** 2015-02-25 18:26 UTC
