### ISSUE TITLE
Random glitch that causes the server to break down.

### ISSUE THREAD

**Issue by danielcbailey** [msummers123/Movecraft-3#129] opened 2015-05-18 01:59 UTC
I was just on the AP public build server testing my new ship, and all of the sudden, my ship starts changing color and the dispensers are reset. This is a glitch that has been around for a while now, but just today it caused the server to crash. Due to the fact that this is not my server, I cannot provide logs or extra data. But, no attention has been put forth to this major issue so I am raising it here. This is especially bad for survival servers as people cannot move, and their stuff is gone, and their ship is trashed.

**Comment by msummers123** [comment] 2015-05-18 02:23
The characterization "no attention has been given" is a little inaccurate. Actually this concerns me greatly. I had hoped it was an issue with items breaking and would be fixed in the latest build, since items no longer break as far as I know. 

But the build server has been running that new build since Friday. So obviously that wasn't it. The problem is that I have never been able to reproduce it in my tests. So I can't figure out what causes it. What we really need is to isolate what makes it start happening.

**Comment by msummers123** [comment] 2015-05-18 02:26
Were you the only one flying a ship at the time? If we can find a ship that definitely causes the plugin to start crashing, that will help narrow down what causes it. It is very possible it could be a specific ship configuration.

**Comment by mwkaicz** [comment] 2015-05-18 11:19
What's the server and Movecraft version? I remember this problem, but it was a year ago. It equals to lost metadata of blocks.

**Comment by Pocketkid2** [comment] 2015-05-18 15:10
Is this related to the weird bug that caused redstone blocks to turn into stone blocks?

**Comment by TylerS1066** [comment] 2015-05-18 20:15
The server is Bacca's build server, movecraft version is the newest build.

And it's not just on bacca's server, I've seen this happen on craftbukkit 1.7.10, spigot 1.8-1.8.3 and paperspigot 1.8.3.

The cause is usually alot of lag.  And I don't think it is every the ship that is the cause, as I have seen this happen to the Goliath, Shadow Refit, Shadow Refit #2, most fighters, and the battlecruiser (I also have seen it to many more that aren't listed).

**Comment by msummers123** [comment] 2015-05-18 21:44
In this case I was able to find the exact cause of the problem and I'm fixing it. However I have thought I had fixed this many times before, and it may crop again in a different part of the code. Therefore, when you see this please make a note of the exact time and give me that plus your time zone so I can find it in the logs and find the error trace. I will update the version of Movecraft in the next few days.

**Comment by msummers123** [comment] 2015-06-03 21:01
I haven't seen this crop up again, it might actually be fixed this time. If not it can always be reopened.

**Closed by msummers123** 2015-06-03 21:01 UTC
