### ISSUE TITLE
MoveCraft portcullis RMove crash

### ISSUE THREAD

**Issue by Pocketkid2** [msummers123/Movecraft-3#90] opened 2015-02-18 05:47 UTC
When I click a valid RMove sign for a controlled portcullis, this crash happens and nothing is showed in the game.

http://pastebin.com/3fqnVY1t

**Comment by msummers123** [comment] 2015-02-18 23:55
It would appear that this is caused by having a space after the comma and before the second number. Apparently it is pretty picky. There should not be any spaces in the coordinates on the sign.

**Comment by msummers123** [comment] 2015-02-25 18:30
I would like to close this, did you have any further questions?

**Closed** 2015-03-02 22:40 UTC
